AWSTemplateFormatVersion: 2010-09-09
Description: Cognito UserPool + Client + Hosted UI Domain

Parameters:
  DomainPrefix:
    Type: String
    Description: Domain prefix for Hosted UI (example → example.auth.ap-northeast-1.amazoncognito.com)

Resources:
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-UserPoolClient"
      UserPoolId: !Ref UserPool
      GenerateSecret: true
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Join ['', ['https://', !Ref DomainPrefix, '.auth.', !Ref AWS::Region, '.amazoncognito.com/oauth2/idpresponse']]
      LogoutURLs:
        - !Join ['', ['https://', !Ref DomainPrefix, '.auth.', !Ref AWS::Region, '.amazoncognito.com/logout']]

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref DomainPrefix
      UserPoolId: !Ref UserPool

Outputs:

  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: CognitoUserPoolArnExport

  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: CognitoClientIdExport

  DomainPrefix:
    Value: !Ref DomainPrefix
    Export:
      Name: CognitoDomainPrefixExport
