AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance using AMI (docker-compose for GitLab/OpenProject)

Parameters:
  AmiId:
    Type: String
    Description: Prebuilt AMI ID containing docker-compose

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref InstanceRole]

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: t3.large
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds:
        - !ImportValue EC2SGId
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: GitLab-OpenProject-Server

Outputs:
  EC2InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: EC2InstanceId
