AWSTemplateFormatVersion: 2010-09-09
Description: ALB + Cognito Auth + Routing to Existing EC2 (VPC ID specified externally)

Parameters:
  EC2InstanceId:
    Type: String
    Description: EC2 instance running docker-compose (GitLab/OpenProject)
    
  VpcId:
    Type: String
    Description: VPC ID where the EC2 exists

  PublicSubnet1:
    Type: String
    Description: Public Subnet ID 1 in the same VPC as the EC2

  PublicSubnet2:
    Type: String
    Description: Public Subnet ID 2 in the same VPC as the EC2

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-docker-ec2
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Scheme: internet-facing
      Type: application

  GitLabTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gitlab-tg
      TargetType: instance
      Port: 8000
      Protocol: HTTP
      VpcId: !Ref VpcId
      Targets:
        - Id: !Ref EC2InstanceId

  OpenProjectTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: openproject-tg
      TargetType: instance
      Port: 4000
      Protocol: HTTP
      VpcId: !Ref VpcId
      Targets:
        - Id: !Ref EC2InstanceId

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 403
            ContentType: text/plain
            MessageBody: "Access Denied"

  GitLabListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - "/gitlab/*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref GitLabTG

  OpenProjectListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - "/openproject/*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref OpenProjectTG

Outputs:
  GitLabTGArn:
    Value: !Ref GitLabTG
    Export:
      Name: GitLabTGArn
  ALBListenerArn:
    Value: !Ref ALBListener
    Export:
      Name: ALBListenerArn
