AWSTemplateFormatVersion: 2010-09-09
Description: Cognito authentication for ALB

Resources:

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: alb-userpool

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: yscode2015-jsp-project-management   # 一意ならOK
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: alb-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

  CognitoAuth:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue ALBListenerArn # alb.yaml から出力されている前提
      Priority: 5
      Conditions:
        - Field: path-pattern
          Values:
            - "/*"
      Actions:
        - Type: authenticate-cognito
          Order: 1
          AuthenticateCognitoConfig:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            UserPoolClientId: !Ref CognitoUserPoolClient
            UserPoolDomain: !Ref CongitoUserPoolDomain
        - Type: forward
          Order: 2
          TargetGroupArn: !ImportValue GitLabTGArn # デフォルトのターゲットグループ
