AWSTemplateFormatVersion: 2010-09-09
Description: ALB + Cognito Auth + Routing to Existing EC2 (VPC ID specified externally)

Parameters:
  ExistingInstanceId:
    Type: String
    Description: EC2 instance running docker-compose (GitLab/OpenProject)
    
  ExistingVpcId:
    Type: String
    Description: VPC ID where the EC2 exists

  PublicSubnet1:
    Type: String
    Description: Public Subnet ID 1 in the same VPC as the EC2

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !Ref ExistingVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: app-alb
      Scheme: internet-facing
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
      Type: application

  GitlabTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref ExistingVpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      Targets:
        - Id: !Ref ExistingInstanceId
          Port: 80

  OpenProjectTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref ExistingVpcId
      Protocol: HTTP
      Port: 4000
      TargetType: instance
      Targets:
        - Id: !Ref ExistingInstanceId
          Port: 4000

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: authenticate-cognito
          Order: 1
          AuthenticateCognitoConfig:
            UserPoolArn: !ImportValue CognitoUserPoolArnExport
            UserPoolClientId: !ImportValue CognitoClientIdExport
            UserPoolDomain: !Sub
              - "${DomainPrefix}.auth.${Region}.amazoncognito.com"
              - DomainPrefix: !ImportValue CognitoDomainPrefixExport
                Region: !Ref AWS::Region
        - Type: forward
          Order: 2
          TargetGroupArn: !Ref GitlabTargetGroup

  GitlabRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values: ["/gitlab*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref GitlabTargetGroup

  OpenProjectRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values: ["/openproject*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref OpenProjectTargetGroup

Outputs:
  AlbDns:
    Value: !GetAtt Alb.DNSName
  
  CognitoLogin:
    Value: !Sub
      - "https://${DomainPrefix}.auth.${Region}.amazoncognito.com/login"
      - DomainPrefix: !ImportValue CognitoDomainPrefixExport
        Region: !Ref AWS::Region
